const {
    VITE_ETH_CONTRACT,
    VITE_STAKESTONE_CONTRACT,
    VITE_STONEVAULT_CONTRACT,
    VITE_GGP_CONTRACT,
    VITE_WORLD_CONTRACT,
    VITE_ITEM_CONTRACT,
    VITE_FEESVAULT_CONTRACT,
} = import.meta.env;

export const ETH_CONTRACT = VITE_ETH_CONTRACT;
export const STAKESTONE_CONTRACT = VITE_STAKESTONE_CONTRACT;
export const STONEVAULT_CONTRACT = VITE_STONEVAULT_CONTRACT;
export const GGP_CONTRACT = VITE_GGP_CONTRACT;
export const WORLD_CONTRACT = VITE_WORLD_CONTRACT;
export const ITEM_CONTRACT = VITE_ITEM_CONTRACT;
export const FEESVAULT_CONTRACT = VITE_FEESVAULT_CONTRACT;